# This workflow will lint with a single version of Python
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        pip install flake8 flake8-bugbear
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --show-source --statistics --count

  pr-lint:
    # Automaticall format code with black https://github.com/psf/black
    # only triggers if the other tests worked, since automatic pushing does not
    # trigger the workflow again
    needs: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout
      - uses: Ahuge/black-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLACK_ARGS: "."
